import IMAGES from '@/assets/images'
import Head from 'next/head'
import Image from 'next/image'
import Home from "./Home"


export default function Index() {
  return (
    <>
      <Head>
        <title>Numan Khalil</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Home />
      {/* <About /> */}

    </>
  )
}