import IMAGES from '@/assets/images'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '@/styles/Home.module.css'
// import Navbar from "./Navbar"
import Home from "./Home"
// import About from './About'


export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Home />
      {/* <About /> */}

    </>
  )
}